{
  description = "p99 latency profiler";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs =
    { self, nixpkgs }:
    let
      lib = nixpkgs.lib;
      systems = [
        "aarch64-darwin"
        "aarch64-linux"
        "x86_64-darwin"
        "x86_64-linux"
      ];
      forAllSystems = f: lib.genAttrs systems (system: f nixpkgs.legacyPackages.${system});
      makeCompletions =
        pkgs: package: shells:
        pkgs.runCommand "p99-completions" { nativeBuildInputs = [ pkgs.installShellFiles ]; } ''
          # Keep completion installation declarative for NixOS and nix-darwin:
          # the CLI prints scripts, and the module places them in the store.
          mkdir -p "$out"
          ${lib.optionalString (builtins.elem "bash" shells) ''
            ${package}/bin/p99 completion bash > p99.bash
            installShellCompletion --cmd p99 --bash p99.bash
          ''}
          ${lib.optionalString (builtins.elem "zsh" shells) ''
            ${package}/bin/p99 completion zsh > _p99
            installShellCompletion --cmd p99 --zsh _p99
          ''}
          ${lib.optionalString (builtins.elem "fish" shells) ''
            ${package}/bin/p99 completion fish > p99.fish
            installShellCompletion --cmd p99 --fish p99.fish
          ''}
          touch "$out"
        '';
      p99Module =
        { config, lib, pkgs, ... }:
        let
          cfg = config.programs.p99;
          defaultPackage = self.packages.${pkgs.stdenv.hostPlatform.system}.default;
          completionsPackage = makeCompletions pkgs cfg.package cfg.completionShells;
        in
        {
          options.programs.p99 = {
            enable = lib.mkEnableOption "p99 latency profiler";

            package = lib.mkOption {
              type = lib.types.package;
              default = defaultPackage;
              defaultText = lib.literalExpression "inputs.p99.packages.\${pkgs.stdenv.hostPlatform.system}.default";
              description = "The p99 package to install.";
            };

            enableCompletions = lib.mkOption {
              type = lib.types.bool;
              default = true;
              description = "Whether to install shell completion files generated by p99.";
            };

            completionShells = lib.mkOption {
              type = lib.types.listOf (lib.types.enum [
                "bash"
                "zsh"
                "fish"
              ]);
              default = [
                "bash"
                "zsh"
                "fish"
              ];
              description = "Shells to generate completions for when completions are enabled.";
            };
          };

          config = lib.mkIf cfg.enable {
            environment.systemPackages = [
              cfg.package
            ] ++ lib.optional cfg.enableCompletions completionsPackage;
          };
        };
    in
    {
      packages = forAllSystems (pkgs: {
        p99 = pkgs.callPackage ./nix/package.nix { };
        completions = makeCompletions pkgs self.packages.${pkgs.stdenv.hostPlatform.system}.p99 [
          "bash"
          "zsh"
          "fish"
        ];
        default = self.packages.${pkgs.stdenv.hostPlatform.system}.p99;
      });

      checks = forAllSystems (pkgs: {
        package = self.packages.${pkgs.stdenv.hostPlatform.system}.p99;
        completions = self.packages.${pkgs.stdenv.hostPlatform.system}.completions;

        module =
          let
            evaluated = lib.evalModules {
              specialArgs = { inherit pkgs; };
              modules = [
                (
                  { lib, ... }:
                  {
                    options.environment.systemPackages = lib.mkOption {
                      type = lib.types.listOf lib.types.package;
                      default = [ ];
                    };
                  }
                )
                p99Module
                {
                  programs.p99.enable = true;
                }
              ];
            };
            packageCount = builtins.length evaluated.config.environment.systemPackages;
          in
          pkgs.runCommand "p99-module-check" { } ''
            test ${toString packageCount} -eq 2
            touch "$out"
          '';
      });

      apps = forAllSystems (pkgs: {
        p99 = {
          type = "app";
          program = "${self.packages.${pkgs.stdenv.hostPlatform.system}.p99}/bin/p99";
          meta = {
            description = "Run the p99 latency profiler";
          };
        };
        default = self.apps.${pkgs.stdenv.hostPlatform.system}.p99;
      });

      overlays.default = final: _prev: {
        p99 = final.callPackage ./nix/package.nix { };
      };

      nixosModules = {
        p99 = p99Module;
        default = self.nixosModules.p99;
      };

      darwinModules = {
        p99 = p99Module;
        default = self.darwinModules.p99;
      };
    };
}
